# Generated by Django 6.0.7 on 2026-07-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("FARMER", "Farmer"),
                    ("BUYER", "Buyer"),
                    ("OPERATOR", "Operator"),
                ],
                default="BUYER",
                max_length=20,
            ),
        ),
    ]
