# Generated by Django 6.0.7 on 2026-07-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_add_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("FARMER", "Farmer"),
                    ("BUYER", "Buyer"),
                    ("OPERATOR", "Operator"),
                ],
                default="BUYER",
                max_length=20,
            ),
        ),
    ]
