# Generated by Django 6.0.7 on 2026-07-18 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="produce",
            name="farmer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="produce",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="produce",
            name="grade",
            field=models.CharField(default="Standard", max_length=50),
        ),
        migrations.AddField(
            model_name="produce",
            name="image_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="produce",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="produce",
            name="location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="produce",
            name="quantity_available_kg",
            field=models.IntegerField(default=0),
        ),
    ]
